{
  "name": "portfolio",
  "version": "1.0.0",
  "description": "Nethra's Portfolio",
  "scripts": {
    "start": "http-server ./"
  },
  "dependencies": {
    "http-server": "^14.0.0"
  }
}
